/**
 * Configuration for fact generation feature
 * These are the predefined options for the research metadata dropdowns
 */

export const FACT_GENERATION_CONFIG = {
  dataTypes: [
    "User Interview",
    "Usability Test",
    "Focus Group",
    "Survey Response",
    "Customer Feedback",
    "Support Ticket",
    "Beta Testing",
    "A/B Test Results",
    "Field Study",
    "Other",
  ],
  products: [
    "Web App",
    "Mobile App",
    "Desktop App",
    "API",
    "Dashboard",
    "Admin Panel",
    "Customer Portal",
    "Internal Tool",
    "Other",
  ],
  features: [
    "Onboarding",
    "Authentication",
    "Dashboard",
    "Reports",
    "Search",
    "Navigation",
    "Checkout",
    "Payment",
    "Settings",
    "Notifications",
    "Profile",
    "Data Export",
    "Analytics",
    "Collaboration",
    "File Upload",
    "Other",
  ],
  themes: [
    "User Behavior",
    "Needs",
    "Painpoint",
    "Visual Design",
    "Expectation",
    "Routine",
    "Security",
    "Motivation",
    "Frustration",
    "Accessibility",
    "Mental Models",
    "Workaround",
    "Language and Terminology",
    "Technical Limitation",
    "Suggestions",
    "Retention Drivers",
    "Decision Making Process",
    "Satisfaction",
    "Preference",
    "Comparative Feedback",
    "Usability",
  ],
} as const
